# 自动改写：task 段 run_mode/trt_fp16 + img_size/[640,640]
wbt_car: 0.1
camera:
  front: 2
  side: 1
io:
  left_sensor: 8
  right_sensor: 7
  light: 2
speed:
  x:
    limit: 0.7
  y:
    limit: 0.7
  angle:
    limit: 3
lane_pid:
  cfg_pid_y:
    Kp: 5
    Ki: 0.1
    Kd: 0
    setpoint: 0
    output_limits:
    - -0.7
    - 0.7
  cfg_pid_angle:
    Kp: 3
    Ki: 0
    Kd: 0
    setpoint: 0
    output_limits:
    - -1.5
    - 1.5
det_pid:
  cfg_pid_y:
    Kp: 1
    Ki: 0
    Kd: 0
    setpoint: 0
    output_limits:
    - -0.7
    - 0.7
  cfg_pid_angle:
    Kp: 1
    Ki: 0
    Kd: 0
    setpoint: 0
    output_limits:
    - -1.5
    - 1.5
location_pid:
  pid_x:
    Kp: -2
    Ki: 0
    Kd: 0
    setpoint: 0
    output_limits:
    - -0.7
    - 0.7
  pid_y:
    Kp: -2
    Ki: 0
    Kd: 0
    setpoint: 0
    output_limits:
    - -0.7
    - 0.7
infer_cfg:
- name: lane
  infer_type: LaneBlendInfer
  model_dir: lane_model
  model_dir_d_e: lane_model_d_e
  port: 5001
  img_size:
  - 128
  - 128
  run_mode: paddle
- name: task
  infer_type: YoloeInfer
  model_dir: task2026
  port: 5002
  img_size:
  - 640
  - 640
  run_mode: paddle
- name: ocr
  infer_type: OCRReco
  det_model_dir: ch_PP-OCRv3_det_infer
  rec_model_dir: ch_PP-OCRv3_rec_infer
  port: 5004
  img_size: null
  run_mode: paddle
ernie_access_token: REPLACE_YOUR_ACCESS_TOKEN_HERE
